import {
  BadgeCheck,
  BarChart3,
  Baby,
  BookOpenText,
  BookText,
  Briefcase,
  Cat,
  CheckSquare,
  Coffee,
  Feather,
  FileText,
  HandHeart,
  HeartPulse,
  Laugh,
  Leaf,
  Megaphone,
  Microscope,
  Palette,
  PartyPopper,
  PencilRuler,
  Rocket,
  ScrollText,
  Shield,
  ShieldCheck,
  Siren,
  Smile,
  Sparkles,
  Stars,
  Target,
  Telescope,
  Theater,
  Zap,
  ListMinus,
  ListChecks,
  MessagesSquare,
  GraduationCap,
} from "lucide-react";
import type {Tone, ToneType} from "./types";

export const DEFAULT_TONE: Tone = "default";

export const TONES: ToneType[] = [
  {
    value: "default",
    label: "Default",
    description: "Balanced, neutral, versatile",
    icon: Sparkles,
  },
  {
    value: "academic",
    label: "Academic",
    description: "Formal, structured, precise, objective",
    icon: GraduationCap,
  },
  {
    value: "business",
    label: "Business",
    description: "Clear, efficient, results-focused",
    icon: Briefcase,
  },
  {
    value: "casual",
    label: "Casual",
    description: "Relaxed, simple, natural",
    icon: Coffee,
  },
  {
    value: "formal",
    label: "Formal",
    description: "Polished, respectful, structured",
    icon: ScrollText,
  },
  {
    value: "conversational",
    label: "Conversational",
    description: "Natural, human-like, engaging",
    icon: MessagesSquare,
  },
  {
    value: "professional",
    label: "Professional",
    description: "Clear, competent, balanced",
    icon: BadgeCheck,
  },

  {
    value: "friendly",
    label: "Friendly",
    description: "Warm and approachable",
    icon: Smile,
  },
  {
    value: "confident",
    label: "Confident",
    description: "Assertive and self-assured",
    icon: ShieldCheck,
  },
  {
    value: "emotional",
    label: "Emotional",
    description: "Expressive and feeling-driven",
    icon: HeartPulse,
  },
  {
    value: "empathetic",
    label: "Empathetic",
    description: "Understanding and supportive",
    icon: HandHeart,
  },
  {
    value: "calm",
    label: "Calm",
    description: "Soft, minimal, peaceful",
    icon: Leaf,
  },
  {
    value: "motivational",
    label: "Motivational",
    description: "Inspiring and action-driven",
    icon: Rocket,
  },
  {
    value: "inspirational",
    label: "Inspirational",
    description: "Uplifting and meaningful",
    icon: Stars,
  },
  {
    value: "dramatic",
    label: "Dramatic",
    description: "Intense and powerful",
    icon: Theater,
  },
  {
    value: "excited",
    label: "Excited",
    description: "Energetic and enthusiastic",
    icon: PartyPopper,
  },
  {
    value: "serious",
    label: "Serious",
    description: "Focused and direct",
    icon: Shield,
  },

  {
    value: "creative",
    label: "Creative",
    description: "Imaginative and unique",
    icon: Palette,
  },
  {
    value: "storytelling",
    label: "Storytelling",
    description: "Narrative-driven with flow",
    icon: BookText,
  },
  {
    value: "poetic",
    label: "Poetic",
    description: "Artistic, rhythmic, expressive",
    icon: Feather,
  },
  {
    value: "descriptive",
    label: "Descriptive",
    description: "Rich details and imagery",
    icon: FileText,
  },
  {
    value: "humorous",
    label: "Humorous",
    description: "Light and witty",
    icon: Laugh,
  },
  {
    value: "playful",
    label: "Playful",
    description: "Fun and informal",
    icon: Cat,
  },
  {
    value: "childfriendly",
    label: "Child Friendly",
    description: "Very simple, clear, gentle",
    icon: Baby,
  },

  {
    value: "simple",
    label: "Simple",
    description: "Easy to understand, minimal complexity",
    icon: CheckSquare,
  },
  {
    value: "concise",
    label: "Concise",
    description: "Short and to the point",
    icon: ListMinus,
  },
  {
    value: "detailed",
    label: "Detailed",
    description: "Thorough and expanded",
    icon: ListChecks,
  },
  {
    value: "analytical",
    label: "Analytical",
    description: "Logical and structured",
    icon: BarChart3,
  },
  {
    value: "critical",
    label: "Critical",
    description: "Evaluative and thoughtful",
    icon: Microscope,
  },
  {
    value: "educational",
    label: "Educational",
    description: "Teaching-oriented",
    icon: BookOpenText,
  },
  {
    value: "explanatory",
    label: "Explanatory",
    description: "Clear step-by-step explanation",
    icon: PencilRuler,
  },

  {
    value: "persuasive",
    label: "Persuasive",
    description: "Convincing and influential",
    icon: Megaphone,
  },
  {
    value: "assertive",
    label: "Assertive",
    description: "Direct and strong",
    icon: Target,
  },
  {
    value: "bold",
    label: "Bold",
    description: "Confident and impactful",
    icon: Zap,
  },
  {
    value: "urgent",
    label: "Urgent",
    description: "Time-sensitive and intense",
    icon: Siren,
  },
  {
    value: "visionary",
    label: "Visionary",
    description: "Future-focused and ambitious",
    icon: Telescope,
  },
];

export const getToneByValue = (tone: Tone) =>
  TONES.find((t) => t.value === tone) ?? TONES[0];
